apps/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^books_cbv/', include("books_cbv.urls", namespace="books_cbv")),
]

books_cbv/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin

from books_cbv import views

urlpatterns = patterns("",
                       url(r"^$", views.BookList.as_view(), name="book_list"),
                       url(r"page/(?P<page>\d+)$", views.BookList.as_view(), name="book_list"),
                       url(r"^new$", views.BookCreate.as_view(), name="book_new"),
                       url(r"^edit/(?P<pk>\d+)$", views.BookUpdate.as_view(), name="book_edit"),
                       url(r"^delete/(?P<pk>\d+)$", views.BookDelete.as_view(), name="book_delete"),
                       url(r"^detail/(?P<pk>\d+)$", views.BookDetail.as_view(), name="book_detail"),
                       )

books_cbv/models.py
from django.core.urlresolvers import reverse
from django.db import models


# Create your models here.

class Book(models.Model):
    name = models.CharField(max_length=200)
    pages = models.IntegerField()

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("books_cbv:book_edit", kwargs={"pk": self.pk})

books_cbv/views.py
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import HttpResponse

# Create your views here.
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from books_cbv.models import Book


class BookList(ListView):
    model = Book
    paginate_by = 3


class BookCreate(CreateView):
    model = Book
    fields = ["name", "pages"]
    success_url = reverse_lazy("books_cbv:book_list")


class BookUpdate(UpdateView):
    model = Book
    fields = ['name', 'pages']
    success_url = reverse_lazy('books_cbv:book_list')


class BookDelete(DeleteView):
    model = Book
    success_url = reverse_lazy('books_cbv:book_list')

class BookDetail(DetailView):
    model = Book

books_cbv/templates/books_cbv/book_confirm_delete.html
<form method="post">
    {% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Submit"/>
</form>

books_cbv/templates/books_cbv/book_detail.html
{{ book.name }}
<br/>
{{ book.pages }}

books_cbv/templates/books_cbv/book_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<form method="post">
    {% csrf_token%}
    {{form.as_p}}
    <input type="submit" value="Submit"/>
</form>

</body>
</html>

books_cbv/templates/books_cbv/book_list.html
<h1>Books CBV</h1>
<ul>
    {% for book in object_list %}
        {#        объекты из базы передаются в list view в переменной object_list#}
        <li>
            {{ book.name }} ({{ book.pages }} Pages)
            <a href="{% url 'books_cbv:book_edit' book.id %}">edit</a>
            <a href="{% url 'books_cbv:book_delete' book.id %}">delete</a>
            <a href="{% url 'books_cbv:book_detail' book.id %}">see details</a>
        </li>
    {% endfor %}

    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="/books_cbv/page/{{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                </span>
                {% if page_obj.has_next %}
                    <a href="/books_cbv/page/{{ page_obj.next_page_number }}">Next</a>

                {% endif %}
            </span>
        </div>

        {% else %}
        <h3>No Books for paginate</h3>
    {% endif %}
</ul>